[project]
name = "uzcode"
version = "0.1.0"
description = "A minimal, stateless AI coding agent"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "tomli-w>=1.2",
    "langgraph>=1.2.9",
    "litellm>=1.92",
    "fastapi>=0.139.0",
    "ddgs>=9.14.4",
    "httpx>=0.28.1",
    "trafilatura>=2.1.0",
    "overdict",
]

[project.scripts]
uzcode = "uzcode.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/uzcode"]

[tool.hatch.build.targets.wheel.force-include]
"src/uzcode/cfgs" = "uzcode/cfgs"

[tool.uv.sources]
overdict = { git = "https://github.com/youzi151/py-overdict" }
