[llm]
base_url = "http://127.0.0.1:8081/v1"
api_key = "1"
model = "1"

[messagelib.__system]
role = "system"
content = "You are a coding agent. Be concise and helpful."

[messagelib.__skill]
role = "system"
content = ""

[tools.sub_agent_done]
enable = false

[extension]
enable = ["logging", "llm_sent"]
[extension.__merge]
enable = "after"