[loop]
auto_loop = true
max_iterations = 10

[tools.read_file]
permission = "approve"

[tools.list_dir]
permission = "approve"

[tools.grep]
permission = "approve"

[tools.write_file]
preview_diff = true
on_failure = "abort"

[tools.edit_file]
preview_diff = true
on_failure = "abort"

[tools.summarize_task]
permission = "approve"

[extension]
enable = ["file_cru", "task_summary"]
[extension.__merge]
enable = "concat"

[exts.task_summary]
auto_open = true
task_summary_path = ".uzcode/summaries"

[extension.order.before_llm]
logging = 10

[extension.order.after_llm]
logging = 100

[extension.order.before_tool]
file_cru = 50